In [18]:
import pandas as pd
from sklearn import naive_bayes
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [19]:
df = pd.read_csv("textTrainData.txt", sep="\t", encoding='latin1')

In [20]:
tf = pd.read_csv("textTestData.txt", sep="\t", encoding="latin1")

In [21]:
df.head()

Sentence  Sentiment
0                                Not a good bargain.          0
1  Well packaged, arrived on time, and works as i...          1
2                     The battery runs down quickly.          0
3  This item worked great, but it broke after 6 m...          0
4  The headsets are easy to use and everyone love...          1

In [22]:
tf.head()

Sentence  Sentiment
0                                Not a good bargain.          0
1  Well packaged, arrived on time, and works as i...          1
2                     The battery runs down quickly.          0
3  This item worked great, but it broke after 6 m...          0
4  The headsets are easy to use and everyone love...          1

In [23]:
#TF-IDF Vectorizer
vectorizer = TfidfVectorizer(use_idf=True, lowercase=True, strip_accents='ascii')

In [24]:
y_train = df.Sentiment

In [25]:
y_test = tf.Sentiment

In [26]:
x_train = vectorizer.fit_transform(df.Sentence)

In [27]:
x_test = vectorizer.transform(tf.Sentence)

In [28]:
print (y_train.shape)
print (x_train.shape)

(2726,)
(2726, 4925)


In [29]:
print(y_test.shape)
print(x_test.shape)

(15,)
(15, 4925)


In [30]:
#Train the Naive Bayes classifier
clf = naive_bayes.MultinomialNB()
clf.fit(x_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [31]:
predictions = clf.predict(x_test)
predictions

array([1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [32]:
print( "Train Accuracy is :", accuracy_score(y_train, clf.predict(x_train)))

Train Accuracy is : 0.95121056493


In [33]:
print( "Test Accuracy is :", accuracy_score(y_test, clf.predict(x_test)))

Test Accuracy is : 0.933333333333


In [34]:
print( " Confusion matrix for train:")
print(confusion_matrix(y_train, clf.predict(x_train)))
print( " Confusion matrix for test :")
print(confusion_matrix(y_test, clf.predict(x_test)))

 Confusion matrix for train:
[[1343   37]
 [  96 1250]]
 Confusion matrix for test :
[[6 1]
 [0 8]]
